apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  namespace: ajp-namespaces
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: 52.79.48.121:30002/ajp-repository/tomcat:harbor
          ports:
            - containerPort: 8080
