apiVersion: v1
kind: Service
metadata:
  name: youtube-nginx
  namespace: ajp-namespaces
spec:
  selector:
    app: youtube-nginx
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: ClusterIP
