apiVersion: v1
kind: Service
metadata:
  name: youtube-nginx
  namespace: ajp-namespaces
spec:
  selector:
    app: youtube-nginx
  ports:
    - nodePort: 31111
      port: 9001
      protocol: TCP
      targetPort: 80
  type: nodePort
