apiVersion: v1
kind: Service
metadata:
  name: hello-nginx
  namespace: ajp-namespaces
spec:
  selector:
    app: hello-nginx
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  type: ClusterIP
