apiVersion: v1
kind: Service
metadata:
  name: hello-nginx
  namespaces: ajp-namespaces
spec:
  selector:
    app: hello-nginx
  ports:
    - nodePort: 31111
      port: 80
      protocol: TCP
      targetPort: 80
  type: NodePort
