apiVersion: v1
kind: Service
metadata:
  name: hello-nginx
  namespace: ajp-namespaces
spec:
  selector:
    app: hello-nginx
  ports:
    - port: 9001
      protocol: TCP
      targetPort: 80
  type: ClusterIP
