apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
  namespace: ajp-namespaces
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 3
  selector:
    matchLabels:
      app: hello-nginx
  template:
    metadata:
      labels:
        app: hello-nginx
    spec:
      containers:
        - name: hello-nginx
          image: 52.79.48.121:30002/ajp-repository/nginx:signup
          ports:
            - containerPort: 80
#          volumeMounts:
#            - name: nginx-config-volume
#              mountPath: /etc/nginx/conf.d/default.conf
#              subPath: nginx.conf
#      volumes:
#        - name: nginx-config-volume
#          configMap:
#            name: nginx-configmap
